# Generated by Django 2.2 on 2019-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jaranOnsen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onsen_name', models.TextField()),
                ('onsen_name_kana', models.TextField()),
                ('onsen_id', models.IntegerField()),
                ('onsen_adress', models.TextField()),
                ('region', models.TextField()),
                ('prefecture', models.TextField()),
                ('large_area', models.TextField()),
                ('small_area', models.TextField()),
                ('nature_of_onsen', models.TextField()),
                ('onsen_area_name', models.TextField()),
                ('onsen_area_id', models.TextField()),
                ('onsen_area_url', models.TextField()),
                ('onsen_area_caption', models.TextField()),
                ('onsen_area_name_kana', models.TextField()),
            ],
        ),
    ]
