# Generated by Django 2.2.1 on 2019-05-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaran_onsen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jaranOnsenPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_area', models.IntegerField()),
                ('count', models.IntegerField()),
                ('xml_ptn', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='jaranonsen',
            old_name='onsen_adress',
            new_name='onsen_address',
        ),
    ]
