# Generated by Django 2.2.1 on 2019-05-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaran_onsen', '0002_auto_20190508_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='jaranonsenpost',
            name='onsen_q',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jaranonsenpost',
            name='pref',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jaranonsenpost',
            name='reg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jaranonsenpost',
            name='s_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jaranonsenpost',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jaranonsen',
            name='onsen_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='jaranonsenpost',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jaranonsenpost',
            name='l_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jaranonsenpost',
            name='xml_ptn',
            field=models.IntegerField(default=0),
        ),
    ]
