# Generated by Django 2.2.1 on 2019-05-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaran_onsen', '0003_auto_20190509_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaranonsen',
            name='onsen_id',
            field=models.IntegerField(),
        ),
    ]
